### ISSUE TITLE
NTP time & NTP Offset is not working?

### ISSUE THREAD

**Issue by NTMS2017** [knezzz/ntp#5]
I try to run the example and I get this error.
I guess this part is not working:

**Error Part:**
Unhandled Exception: SocketException: Failed host lookup: '**pool.ntp.org**' (OS Error: No address associated with hostname, errno = 7)

**Full Error:**
```
Launching lib/main.dart on SM G935F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM G935F...
E/flutter (10544): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed host lookup: 'pool.ntp.org' (OS Error: No address associated with hostname, errno = 7)
E/flutter (10544): #0      _NativeSocket.lookup.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:386:9)
E/flutter (10544): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (10544): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10544): #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (10544): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (10544): #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (10544): #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (10544): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (10544): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (10544): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (10544): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (10544): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (10544): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10544): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10544): 
D/libGLESv2(10544): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.ntp_time
```

**Comment by NTMS2017** [comment]
same as https://github.com/knezzz/ntp/issues/4 and working now. thanks
